import Header from "@/components/Header";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { SiTypescript } from "react-icons/si";
import Project from "@/components/Project";
import IndTool from "@/components/IndTool";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ayomide Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-[#999] py-1">
        <nav className="sticky top-0 border-b border-b-neutral-800 bg-dark bg-opacity-70 backdrop-blur-lg ">
          <section className="max-w-[60rem] mx-auto ">
            <Header />
          </section>
        </nav>
        <main className="px-4">
          <section className="max-w-[60rem] mx-auto mt-4">
            <h1 className="font-bold text-white text-2xl mb-2">
              Hi, I&apos;m Ayomide
            </h1>
            <p className="">
              I&apos;m a{" "}
              <span className="text-green-700">Software Developer</span>. I
              enjoy <span className="text-green-700">Building </span> things and
              seeing new things come to life with code. I do enjoy{" "}
              <span className="text-green-700">experimenting</span> a lot on new
              tech and tools and i am a huge learner. I am huge on some{" "}
              <span className="text-green-700">stuff</span> : AI, Drone
              Technology, International Politics etc and i feel ML is boring
              LoL.
            </p>
          </section>

          <section id="tools" className="max-w-[60rem] mx-auto mt-8">
            <h1 className="font-bold text-white text-2xl mb-2">Tools</h1>
            <p className="">
              Over the course of my coding Journey i have come across many tools
              and services. My Prim ary Stack includes React on the frontend and
              Nodejs on the backend. I have listed some of the languages/tools i
              use below.
            </p>
            <aside className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-4 gap-x-2 space-y-2">
              <IndTool name="React" />
              <IndTool name="PostgreSQL" />
              <IndTool name="TailwindCSS" />
              <IndTool name="Git" />
            </aside>
            <aside className="w-full border rounded-lg border-neutral-500 py-4 px-2 mt-4">
              <p>
                Things i am currently learning on plan to learn in the near
                future
              </p>
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-4 gap-x-2 space-y-2 px-2">
                <IndTool name="React" />
                <IndTool name="PostgreSQL" />
                <IndTool name="TailwindCSS" />
                <IndTool name="Git" />
              </div>
            </aside>
          </section>

          <section id="projects" className="max-w-[60rem] mx-auto mt-8 pb-4 ">
            <h2 className="font-bold text-white text-2xl mb-2">Projects</h2>
            <p className="">
              I like to build things i will use or find interesting. It may be
              stuff i find on the internet or things am genuinly need.Here are a
              couple of them, you can find other one&apos;s on my github.
            </p>
            <Project
              name="Shop It"
              desc="An Ecommerce app with a cms (Sanity Cms) with checkout available"
            />
          </section>

          <section>
            <h2 className="text-white font-medium text-2xl ">Connect</h2>
            <p>Have an idea or want to contact me? get in touch below</p>

            {/* <div>
              <div className="flex justify-between">
              <button>Send a mail</button>
              <button>&gt;</button>
              </div>

            </div> */} 
            {/* form div above */}
            
            <div>
              <p>Go the fast way, hit me</p>
              <button></button>
            </div>
          </section>
        </main>
        <footer className=" max-w-[72rem] mx-auto border-t border-t-neutral-800 p-2">
          <section className="">
            <h6 className="text-sm text-neutral-700">2023 Ayomide.</h6>
          </section>
        </footer>
      </main>
    </>
  );
}
