import Header from "@/components/Header";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Project from "@/components/Project";
import IndTool from "@/components/IndTool";
import Footer from "@/components/Footer";
import { BsLinkedin } from "react-icons/bs";
import { MdArrowForward } from "react-icons/md";
import {
  FaTwitterSquare,
  FaInstagramSquare,
  FaGithubSquare,
} from "react-icons/fa";
import aboutImage from "@/assets/20230330_24542.jpg";
import FutureTools from "@/components/FutureTools";
import noteApp from "@/assets/Screenshot (187).png";
import netflixClone from "@/assets/Screenshot (191).png";
import amazonClone from "@/assets/Screenshot (193).png";
import miniGallery from "@/assets/Screenshot (195).png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ayomide Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-[#999] py-1">

        <nav className="sticky top-0 border-b border-b-neutral-800  backdrop-blur-lg ">
          <section className="max-w-[60rem] mx-auto ">
            <Header />
          </section>
        </nav>

        <main className="px-4">
          
          <section className="max-w-[60rem] mx-auto mt-4">
            <div className="w-24 md:w-48 rounded-lg overflow-hidden">
              <Image
                src={aboutImage}
                alt="aboutImage"
                className="h-full w-full"
              />
            </div>
            <h1 className="font-bold text-white text-2xl mb-2 mt-8">
              Hi, I&apos;m Ayomide
            </h1>
            <p className="">
              I&apos;m a{" "}
              <span className="text-green-700">Software Developer</span>. I
              enjoy <span className="text-green-700">Building </span> things and
              seeing new things come to life with code. I do enjoy{" "}
              <span className="text-green-700">experimenting</span> a lot on new
              tech and tools and i am a huge learner. I am huge on some{" "}
              <span className="text-green-700">stuff</span> : AI, Drone
              Technology, International Politics etc and i feel ML is boring
              lol.
            </p>
          </section>

          <section id="tools" className="max-w-[60rem] mx-auto mt-8">
            <h1 className="font-bold text-white text-2xl mb-2 ">Tools</h1>
            <p className="">
              Over the course of my coding Journey i have come across many tools
              and services. My Primary Stack includes React on the frontend and
              Nodejs on the backend. I have listed some of the languages/tools i
              use below.
            </p>
            <aside className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-4 gap-x-2 gap-y-4 ">
              <IndTool />
            </aside>
            <aside className="w-full border rounded-lg border-neutral-500 py-4 px-2 mt-4">
              <div className="flex items-center gap-2">
                <MdArrowForward className="h-5 w-5" />
                <p>
                  Things i am currently learning on plan to learn in the near
                  future
                </p>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-4 gap-x-2 gap-y-4 px-2">
                <FutureTools />
              </div>
            </aside>
          </section>

          <section
            id="projects"
            className="max-w-[60rem] mx-auto mt-8 pb-4 border-b border-b-neutral-900"
          >
            <h2 className="font-bold text-white text-2xl mb-2 ">Projects</h2>
            <p className="">
              I like to build things i will use or find interesting. It may be
              stuff i find on the internet or things am genuinly need.Here are a
              couple of them, you can find other one&apos;s on my github.
            </p>
            <div className="flex flex-col gap-6 mt-4">
              <Project
                name="Note App"
                desc="Create, update and delete notes. local storage to save created notes."
                image={noteApp}
                first={true}
                projectlink="note-app-ruddy.vercel.app/"
                github="github.com/Ayothegod/note-tut"
                />
              <Project
                name="Netflix Clone"
                desc="A simple amazon clone, with firebase for sign-in. include preview movie, save favourite, delete favourite, sign-out and more."
                image={netflixClone}
                first={false}
                projectlink="fullstack-netflix-theta.vercel.app"
                github="github.com/Ayothegod/fullstack-netflix"
                />
              <Project
                name="Simple Amazon Clone"
                desc="A simple Amazon e-commerce app, using react and include cart."
                image={amazonClone}
                first={true}
                projectlink="2022-amazon-clone.vercel.app"
                github="github.com/Ayothegod/2022-amazonClone"
              />
            </div>
          </section>

          <section className="max-w-[60rem] mx-auto mt-4 pb-4">
            <h2 className="text-white font-medium text-2xl ">Connect</h2>
            <p>Have an idea or want to contact me? get in touch below</p>

            <div className="">
              <p>Go the fast way, hit me</p>
              <div className="grid grid-cols-2 sm:grid-cols-4 mt-4 gap-y-2">
                <Link href="https://linkedin.com/in/aiiomide">
                  <button className="flex items-center gap-2 hover:text-blue-700">
                    <BsLinkedin /> <p>Linkedin</p>
                  </button>
                </Link>
                <Link href="https://twitter.com/aiiomide">
                  <button className="flex items-center gap-2 hover:text-blue-400 ">
                    <FaTwitterSquare /> <p>Twitter</p>
                  </button>
                </Link>
                <Link href="https://github.com/ayothegod">
                  <button className="flex items-center gap-2 hover:text-neutral-700 ">
                    <FaGithubSquare /> <p>Github</p>
                  </button>
                </Link>
                {/* <Link href="/">
                  <button className="flex items-center gap-2 hover:text-red-500 ">
                    <FaInstagramSquare /> <p>Instagram</p>
                  </button>
                </Link> */}
              </div>
            </div>
          </section>

        </main>
        <Footer />
      </main>
    </>
  );
}
